In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4,5]

In [4]:
arr = np.array(list1)

In [5]:
arr2 = np.asarray(list1)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr2

array([1, 2, 3, 4, 5])

In [8]:
arr.tolist()

[1, 2, 3, 4, 5]

In [9]:
arr_range = np.arange(10)
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
arr.shape

(5,)

In [12]:
arr.ndim

1

In [13]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [14]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
arr.reshape(1,-1)

array([[1, 2, 3, 4, 5]])

In [16]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3, 4, 5]])

In [18]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
arr2 = np.linspace(1,50, 100)

In [20]:
arr2 = arr2.reshape(10, 10)

In [21]:
arr2.shape

(10, 10)

In [22]:
arr2.ndim

2

In [23]:
np.nan

nan

In [24]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr22 = np.linspace(0,10, 100).reshape(10,10)

In [28]:
arr22[0, :]

array([0.        , 0.1010101 , 0.2020202 , 0.3030303 , 0.4040404 ,
       0.50505051, 0.60606061, 0.70707071, 0.80808081, 0.90909091])

In [29]:
arr22[:, 1]

array([0.1010101 , 1.11111111, 2.12121212, 3.13131313, 4.14141414,
       5.15151515, 6.16161616, 7.17171717, 8.18181818, 9.19191919])

In [30]:
ones = np.eye(3,3)
ones

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
ones[1:, 1:]

array([[1., 0.],
       [0., 1.]])

In [32]:
arr22[ [6,2,5], :]

array([[6.06060606, 6.16161616, 6.26262626, 6.36363636, 6.46464646,
        6.56565657, 6.66666667, 6.76767677, 6.86868687, 6.96969697],
       [2.02020202, 2.12121212, 2.22222222, 2.32323232, 2.42424242,
        2.52525253, 2.62626263, 2.72727273, 2.82828283, 2.92929293],
       [5.05050505, 5.15151515, 5.25252525, 5.35353535, 5.45454545,
        5.55555556, 5.65656566, 5.75757576, 5.85858586, 5.95959596]])

In [33]:
zeros = np.zeros(shape=(3,3))

In [34]:
ones = np.ones(9).reshape(3,3)

In [35]:
np.concatenate( (zeros, ones), axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [36]:
mat1 = np.random.randint(low=1, high=50, size=9).reshape(3,3)
mat2 = np.random.randint(low=1, high=50, size=9).reshape(3,3)

In [37]:
mat1

array([[ 7,  8,  4],
       [45, 43, 14],
       [ 7, 36, 28]])

In [38]:
mat2

array([[20, 30, 48],
       [31, 34, 32],
       [11,  2, 16]])

In [39]:
vec1 = np.array([1,2,3])

In [40]:
mat1 + vec1

array([[ 8, 10,  7],
       [46, 45, 17],
       [ 8, 38, 31]])

In [41]:
mat1 + mat2

array([[27, 38, 52],
       [76, 77, 46],
       [18, 38, 44]])

In [42]:
mat1 * mat2

array([[ 140,  240,  192],
       [1395, 1462,  448],
       [  77,   72,  448]])

In [43]:
mat1.dot(mat2)

array([[ 432,  490,  656],
       [2387, 2840, 3760],
       [1564, 1490, 1936]])

In [44]:
np.dot(mat1, mat2)

array([[ 432,  490,  656],
       [2387, 2840, 3760],
       [1564, 1490, 1936]])

In [45]:
np.matmul(mat1, mat2)

array([[ 432,  490,  656],
       [2387, 2840, 3760],
       [1564, 1490, 1936]])

In [46]:
mat1

array([[ 7,  8,  4],
       [45, 43, 14],
       [ 7, 36, 28]])

In [47]:
mat1.min(axis=0)

array([7, 8, 4])

In [48]:
mat1.argmin(axis=0)

array([0, 0, 0])

In [49]:
mat1.flatten()

array([ 7,  8,  4, 45, 43, 14,  7, 36, 28])

In [50]:
np.ravel(mat1)

array([ 7,  8,  4, 45, 43, 14,  7, 36, 28])

In [51]:
mat1

array([[ 7,  8,  4],
       [45, 43, 14],
       [ 7, 36, 28]])

In [52]:
mat1.astype(np.int64)

array([[ 7,  8,  4],
       [45, 43, 14],
       [ 7, 36, 28]])